-- MySQL Script generated by MySQL Workbench
-- Wed Jun 13 15:39:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_sysdonation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sysdonation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sysdonation` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `db_sysdonation` ;

-- -----------------------------------------------------
-- Table `db_sysdonation`.`tbl_persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sysdonation`.`tbl_persons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `site` VARCHAR(45) NULL,
  `address` VARCHAR(255) NULL,
  `cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sysdonation`.`tbl_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sysdonation`.`tbl_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `tbl_persons_id` INT NOT NULL,
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `fk_tbl_users_tbl_persons1_idx` (`tbl_persons_id` ASC),
  CONSTRAINT `fk_tbl_users_tbl_persons1`
    FOREIGN KEY (`tbl_persons_id`)
    REFERENCES `db_sysdonation`.`tbl_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sysdonation`.`tbl_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sysdonation`.`tbl_profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NULL,
  `fotoprofile` VARCHAR(45) NULL,
  `profissao` VARCHAR(45) NULL,
  `tbl_persons_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tbl_profile_tbl_persons1_idx` (`tbl_persons_id` ASC),
  CONSTRAINT `fk_tbl_profile_tbl_persons1`
    FOREIGN KEY (`tbl_persons_id`)
    REFERENCES `db_sysdonation`.`tbl_persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sysdonation`.`tbl_payment_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sysdonation`.`tbl_payment_methods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `client_id` VARCHAR(255) NOT NULL,
  `client_secret` VARCHAR(255) NOT NULL,
  `tbl_users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tbl_payment_methods_tbl_users1_idx` (`tbl_users_id` ASC),
  CONSTRAINT `fk_tbl_payment_methods_tbl_users1`
    FOREIGN KEY (`tbl_users_id`)
    REFERENCES `db_sysdonation`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sysdonation`.`tbl_goals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sysdonation`.`tbl_goals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `goal` VARCHAR(255) NOT NULL,
  `tbl_users_id` INT NOT NULL,
  `dtregister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tbl_goals_tbl_users1_idx` (`tbl_users_id` ASC),
  CONSTRAINT `fk_tbl_goals_tbl_users1`
    FOREIGN KEY (`tbl_users_id`)
    REFERENCES `db_sysdonation`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sysdonation`.`tbl_donations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sysdonation`.`tbl_donations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DOUBLE NOT NULL,
  `tbl_goals_id` INT NOT NULL,
  `tbl_users_id` INT NOT NULL,
  `donor_name` VARCHAR(255) NOT NULL,
  `donor_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tbl_donations_tbl_goals1_idx` (`tbl_goals_id` ASC),
  INDEX `fk_tbl_donations_tbl_users1_idx` (`tbl_users_id` ASC),
  CONSTRAINT `fk_tbl_donations_tbl_goals1`
    FOREIGN KEY (`tbl_goals_id`)
    REFERENCES `db_sysdonation`.`tbl_goals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_donations_tbl_users1`
    FOREIGN KEY (`tbl_users_id`)
    REFERENCES `db_sysdonation`.`tbl_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sysdonation`.`tbl_receipts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sysdonation`.`tbl_receipts` (
  `id` INT NOT NULL,
  `dtemission` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `tbl_donations_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tbl_receipts_tbl_donations1_idx` (`tbl_donations_id` ASC),
  CONSTRAINT `fk_tbl_receipts_tbl_donations1`
    FOREIGN KEY (`tbl_donations_id`)
    REFERENCES `db_sysdonation`.`tbl_donations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
